const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');

(async () => {
  fs.mkdirSync('artifacts', { recursive: true });
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    const root = process.env.SOCORRO_TEST_URL || 'http://127.0.0.1:5001';
    const loadImages = () => page.locator('img').evaluateAll(async images => {
      images.forEach(image => { image.loading = 'eager'; });
      await Promise.all(images.map(image => image.decode()));
    });
    await page.goto(root);
    assert.equal(await page.locator('.department-row:visible').count(), 22);
    await page.getByRole('radio', { name: 'Legislative', exact: true }).check();
    assert.equal(await page.locator('.department-row:visible').count(), 2);
    await page.locator('#department-search').fill('health');
    assert(await page.locator('#department-empty').isVisible());
    await page.getByRole('radio', { name: 'Executive', exact: true }).check();
    assert.equal(await page.locator('.department-row:visible').count(), 1);
    await page.locator('#department-search').fill('');
    await page.getByRole('radio', { name: 'All offices', exact: true }).check();
    await page.locator('.department-row[data-branch="legislative"]').first().locator('summary').click();
    await page.locator('.department-row[data-branch="legislative"]').first().getByRole('link', { name: 'View office' }).click();
    assert(page.url().endsWith('/departments/sangguniang-bayan/'));
    assert(await page.locator('h1').getByText('Sangguniang Bayan Office').isVisible());
    await page.locator('#office-inquiry button[type="submit"]').click();
    assert.equal(await page.locator('#office-inquiry input[name="name"]').evaluate(input => input.validity.valueMissing), true);
    await page.goto(`${root}/departments/?branch=legislative`);
    assert.equal(await page.locator('.department-row:visible').count(), 2);
    await page.goto(root);
    await loadImages();
    assert.equal(await page.locator('.mayor-message > p').count(), 7);
    assert((await page.locator('.mayor-message').textContent()).includes('timeless tradition'));
    assert((await page.locator('.mayor-quote').textContent()).includes('Lajo pa ta, pero lajo na ta.'));
    await page.locator('.mayor-section').screenshot({ path: 'artifacts/mayor-desktop.png', style: '.site-header { visibility: hidden; }' });
    assert(await page.locator('#vice-mayor').isVisible());
    await page.locator('#vice-mayor summary').click();
    assert(await page.locator('#vice-mayor details').getAttribute('open') !== null);
    assert(await page.locator('#vice-mayor').getByText('Mabuhay ang Isla sa Paglaum!', { exact: true }).isVisible());
    await page.locator('#vice-mayor summary').click();
    assert.equal(await page.locator('.editorial-grid .media-card').count(), 3);
    assert(!(await page.locator('main').textContent()).includes('Sample Blog'));
    await page.screenshot({ path: 'artifacts/home-desktop.png', fullPage: true });
    assert.equal(await page.locator('.destination-tile').count(), 5);
    await page.locator('.destination-band').screenshot({ path: 'artifacts/destinations-desktop.png' });
    await page.getByRole('link', { name: 'Explore Giant Mangroves', exact: true }).click();
    assert(page.url().endsWith('/tourism/#giant-mangroves'));
    assert(await page.locator('#giant-mangroves').isVisible());
    await page.goto(root);
    await page.getByRole('tab', { name: "I'm visiting" }).click();
    assert(await page.locator('#panel-visitor').isVisible());
    assert(!(await page.locator('#panel-resident').isVisible()));
    await page.getByRole('tab', { name: "I'm visiting" }).press('ArrowRight');
    assert(await page.locator('#panel-business').isVisible());
    await page.locator('[data-open-search]').click();
    assert(await page.locator('#site-search').isVisible());
    await page.locator('#global-query').fill('health');
    await page.locator('#global-query').press('Enter');
    assert(await page.getByRole('link', { name: 'Health Services' }).isVisible());
    await page.getByRole('link', { name: 'Health Services' }).click();
    assert.equal(await page.locator('#request-service').inputValue(), 'Health Services');
    await page.locator('#service-filter').fill('agriculture');
    assert.equal(await page.locator('.service-directory-item:visible').count(), 1);
    await page.locator('[data-select-service="Agriculture Support"]').click();
    assert.equal(await page.locator('#request-service').inputValue(), 'Agriculture Support');
    await page.locator('#service-filter').fill('no-such-service');
    assert(await page.locator('#service-empty').isVisible());
    await page.goto(`${root}/tourism/`);
    await page.locator('[data-experience="0"]').click();
    await page.locator('[data-experience="1"]').click();
    await page.locator('#visit-date').fill('2026-12-10');
    await page.reload();
    assert.equal(await page.locator('#visit-list li').count(), 2);
    assert.equal(await page.locator('#visit-date').inputValue(), '2026-12-10');
    const download = page.waitForEvent('download');
    await page.locator('#download-plan').click();
    const result = await download;
    assert.equal(result.suggestedFilename(), 'my-socorro-visit.txt');
    assert(fs.readFileSync(await result.path(), 'utf8').includes('2026-12-10'));
    await page.getByRole('button', { name: 'Remove Sohoton Cove' }).click();
    assert.equal(await page.locator('#visit-list li').count(), 1);
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
    await page.screenshot({ path: 'artifacts/tourism-desktop.png', fullPage: true });
    await page.locator('#clear-plan').click();
    assert(await page.locator('#download-plan').isDisabled());
    for (const width of [1440, 768, 390, 320]) {
      await page.setViewportSize({ width, height: 900 });
      for (const route of ['/', '/services/', '/tourism/', '/about/', '/news/', '/events/', '/transparency/', '/contact/', '/news/soemco-30th-assembly-2026/', '/news/harog-festival-2026/', '/news/soces-aflatoun-partnership-2025/', '/departments/', '/departments/sanggunian-secretary/', '/departments/agricultural-biosystems-engineering/', '/departments/track/', '/staff/login/']) {
        await page.goto(root + route);
        await loadImages();
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${route} overflows at ${width}px`);
        assert.equal(await page.locator('img').evaluateAll(images => images.filter(img => !img.complete || !img.naturalWidth).length), 0, `Broken images: ${route}`);
      }
    }
    await page.goto(`${root}/news/soces-aflatoun-partnership-2025/`);
    await loadImages();
    assert.equal(await page.locator('.article-gallery img').count(), 2);
    assert(await page.locator('.article-sources a').isVisible());
    await page.screenshot({ path: 'artifacts/event-article-mobile.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(root);
    await loadImages();
    await page.locator('#departments').screenshot({ path: 'artifacts/departments-mobile.png', style: '.site-header,.back-top { visibility: hidden; }' });
    await page.screenshot({ path: 'artifacts/home-mobile.png', fullPage: true });
    await page.locator('.mayor-section').screenshot({ path: 'artifacts/mayor-mobile.png', style: '.site-header { visibility: hidden; }' });
    await page.locator('.destination-band').screenshot({ path: 'artifacts/destinations-mobile.png' });
    await page.locator('.nav-toggle').click();
    assert(await page.locator('#primary-nav').isVisible());
    await page.locator('.nav-toggle').press('Escape');
    assert(!(await page.locator('#primary-nav').isVisible()));
    await page.locator('[data-open-search]').click();
    await page.locator('#global-query').press('Escape');
    assert(!(await page.locator('#site-search').isVisible()));
    await page.goto(`${root}/tourism/`);
    await page.screenshot({ path: 'artifacts/tourism-mobile.png', fullPage: true });
    assert.deepEqual(errors, []);
    console.log('PASS: tabs, keyboard navigation, search, service filtering/selection, saved visit plan, download, removal, reset, mobile menu, images and overflow at 4 viewport widths.');
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
